spring:
  application:
    name: admin-client

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
   # health-check-url-path: /actuator/health

  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

server:
  port: 8762
